version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: pokestore-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - pokestore-data:/var/lib/postgresql/data

volumes:
  pokestore-data:
