version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: pokestore-db
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: pokestore
    ports:
      - "5433:5432"
    volumes:
      - pokestore-data:/var/lib/postgresql/data

volumes:
  pokestore-data:
